### PR TITLE
Added some information to the German Aufbauanleitung

### PR DESCRIPTION
**Pull request by M-a-r-i-a-n-n-e**
@WwwBoehriDe as discussed via email, I added some information to the Aufbauanleitung, which I felt would be good to know.

### CODE REVIEW

**Comment by rexfue** [comment]
Thank you. 
@WwwBoehriDe do you agree?  Then i will merge.

**Comment by ThomasWaldmann** [comment]
Pity that we still have formats that can not be reviewed on the web by getting a "diff" display of just the changes.

**Comment by M-a-r-i-a-n-n-e** [comment]
> Pity that we still have formats that can not be reviewed on the web by getting a "diff" display of just the changes.

I totally agree and vote for Markdown (as LaTeX might be inappropriate).

**Comment by rexfue** [comment]
I also vote for MarkDown.

**Comment by ThomasWaldmann** [comment]
Our docs use reST markup and are hosted on readthedocs.

**Comment by M-a-r-i-a-n-n-e** [comment]
@ThomasWaldmann Is there a pipeline that compiles it automatically after a pull request?
Regarding the translation: how can someone start with the German part, without having to translate everything first?
I could do it tomorrow, so a quick response would be greatly appreciated.
P.S. We are discussing this topic in BigBlueButton right now, maybe you want to join?

**Comment by ThomasWaldmann** [comment]
Yes. Github changes should trigger a rebuild on readthedocs.

Original docs shall be in english because translations start from there.

Due to history in this project, here are a lot of german original docs, too, though.

**Comment by ThomasWaldmann** [comment]
I can join the BBB session if i can help, but I don't have any information about that yet.

**Comment by M-a-r-i-a-n-n-e** [comment]
Yes it would help! Thank you! You got mail with the URL.

**Pull request merged**
