### PR TITLE
docs: add deployment guide (en), rst format

### PR DESCRIPTION
**Pull request by ThomasWaldmann**
looks like this when the rendered html file is directly viewed in the browser:

[deployment.pdf](https://github.com/ecocurious2/MultiGeiger/files/4672567/deployment.pdf)

on readthedocs, there would be also some navigation at the left side (and maybe other theme additions).

Issues / TODO:

multigeiger image needs to get A B C labels

garden plan image should also have A B C ... labels rather than german text inside the image (we can translate in rst text part, but we can not translate inside an image).

proof reading by native speaker

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
Also, the table markup is a bit ugly on github diff display.

I used it to place the text to the left of the multigeiger picture.

**Comment by ThomasWaldmann** [comment]
@WwwBoehriDe ^^^

**Comment by WwwBoehriDe** [comment]
Cool to have the english document.

**Comment by ThomasWaldmann** [comment]
@WwwBoehriDe after the german strings are entered on transifex, it will generate the german document from same source.

**Comment by ThomasWaldmann** [comment]
Considering that Marianne works on these docs, too, I merged this now "as is" (content-wise) so there won't be blocking or double work.

If there is any content that needs changing here, it can be done later.

**Pull request merged**
