### PR TITLE
TLS support

### LINKED ISSUE #184: Use TLS (https) for API access?
Moin,

If I'm not mistaken, currently we're using (unencrypted) http only to access the APIs:
https://github.com/ecocurious2/MultiGeiger/blob/master/multigeiger/multigeiger.ino#L198

What's the reason for this? The ESP32 should have enough power - do the libraries we use support TLS? Have we done a test for this yet?

Regards, J.

### PR DESCRIPTION
**Pull request by ThomasWaldmann**
- added NTP support (for TLS, we should have correct date/time)
- added persistent per-server connection instances
- use keep-alive for connections
- add the required CA certs for sensor community, madavi, toilet
- use TLS (https) for data transmission

I did not practically test it yet, but reused some tested code.

Fixes #184.

### CODE REVIEW

**Comment by rexfue** [comment]
I think we should release version 1.13 first and add new features in 1.14

**Comment by ThomasWaldmann** [comment]
I agree, but I can still work on new stuff in a separate branch until master branch is release-ready.

**Comment by rexfue** [comment]
Sure. Ca you do the release now??

**Comment by ThomasWaldmann** [comment]
Not ready yet, see #233 and #235 feedback.

**Comment by rexfue** [comment]
May be I can test this later this week or next week. But Rajko (sensor.community) answer a question about HTTPS on all sensors:
"Won't work. HTTPS for all sensors would overload our servers.
And what would be the benefit? We are an open data platform."
See https://github.com/opendata-stuttgart/sensors-software/pull/685

So I think we should not use TLS to send to sensor.community. But it will sure be useful for firmware updates.

**Comment by ThomasWaldmann** [comment]
@rexfue I added a comment there. And please read #184 about (not) doing firmware updates over https.

**Comment by ThomasWaldmann** [comment]
BTW, even if some server operators are unsure about whether they can offer https, we could still support it in the multigeiger and then use https: or http: URLs depending on the server.

**Comment by ThomasWaldmann** [comment]
rebased on current master to fix conflicts.

**Comment by ThomasWaldmann** [comment]
@rexfue @WwwBoehriDe 

Guess we should merge this soon before we run into merge conflicts.
Maybe we can discuss this in our meeting later today.

**Pull request merged**
