### PR TITLE
adapted to iotwebconf 3.0

### PR DESCRIPTION
**Pull request by rexfue**

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
if the user did not enter values yet (like after flashing the new firmware), does it default to the settings in `userdefines.h` and initialize the strings using these values?

**Comment by ThomasWaldmann** [comment]
did you try OTA update already?

**Comment by rexfue** [comment]
not yet. will check.

**Comment by rexfue** [comment]
OK, tested both - they work.

**Comment by ThomasWaldmann** [comment]
Looks like there is a conflict now. Intend to merge this **after** 1.15.1.

Did you test with iotwebconf 3.0.2?

**Comment by rexfue** [comment]
I don't understand, why there is still the conflict. I pulled the master, rebased the branch to master and pushed it.
Btw. I have tested with IotWebConf 3.0.2 -> everything works as expected on both hardwares , also OTA works.

**Comment by rexfue** [comment]
Made an new PR to avoid merge conflict

**Pull request closed without merging**
