### PR TITLE
multigeiger cleanups

### PR DESCRIPTION
**Pull request by ThomasWaldmann**
lots of cleanups, guess best reviewed by looking at the individual commits.

### CODE REVIEW

**Comment by rexfue** [comment]
I would leave speaker_ticks etc as variable. If we change to set them using the web server, we need them as variable.

**Comment by ThomasWaldmann** [comment]
speaker_ticks as a variable is not needed as of now.

if we get a settings module or an extended webconf module in future, it can be easily re-added there (together with a `extern ...` declaration in the respective header file).

**Comment by ThomasWaldmann** [comment]
merge?

**Comment by rexfue** [comment]
Yeah

**Pull request merged**
