### PR TITLE
update translations

### PR DESCRIPTION
**Pull request by ThomasWaldmann**
note: en/LC_MESSAGES/assemblyguide.po is de -> en

@M-a-r-i-a-n-n-e ^^^

### CODE REVIEW

**Comment by M-a-r-i-a-n-n-e** [comment]
Oh, I have not seen it and did some translations in Transifex already.

**Comment by ThomasWaldmann** [comment]
@M-a-r-i-a-n-n-e usually nothing should get lost, the whole gettext/po-files based workflow is rather based on **merging** than replacing.

but maybe better check (you know better what you've already translated).

**Comment by M-a-r-i-a-n-n-e** [comment]
Good to know! Have you tried to merge the files of this pull request with transifex? If this works then everything is fine. 🙂

**Comment by ThomasWaldmann** [comment]
The workflow I followed is like documented, in short:
- tx push  # from git to transifex
- translate there on transifex (i did some translations, but not all)
- tx pull
- add new or changed files, commit, make PR

**Comment by ThomasWaldmann** [comment]
merged this, so we are ready for next iteration...

**Comment by M-a-r-i-a-n-n-e** [comment]
@ThomasWaldmann In transifex I still see my suggestions in https://www.transifex.com/thomaswaldmann/multigeiger/translate/#de/docs_build_gettext_deployment/318905646 and first suggestions for https://www.transifex.com/thomaswaldmann/multigeiger/translate/#de/docs_build_gettext_assemblyguide/318905593 so everything seems to be ok.

**Pull request merged**
