### PR TITLE
Add support for J306 GM tube

### PR DESCRIPTION
**Pull request by rexfue**
Added tube J306 to tube table

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
https://github.com/kizniche/ttgo-tbeam-ttn-tracker/issues/45 maybe try this.

**Comment by ThomasWaldmann** [comment]
or this https://github.com/lnlp/LMIC-node/issues/41 .

**Comment by rexfue** [comment]
OK, I'll try this tomorrow an do a new PR

**Comment by t-pi** [comment]
just added a separate PR to fix hal_init error

**Pull request closed without merging**
