### PR TITLE
status display: add init status ("?"), docs, fixes #295

### LINKED ISSUE #295: Status display after reset
Should the characters for the servers (s, m, t) not appear directly after reset if enabled?

### PR DESCRIPTION
**Pull request by ThomasWaldmann**

### CODE REVIEW

**Comment by rexfue** [comment]
Looks good. I would prefer exclamation mark instead of question mark. But that's not important.

**Comment by t-pi** [comment]
Actually, ! would feel more like an error to me. I'd prefer ?

**Comment by rexfue** [comment]
OK, 2 : 1  - ? wins :-)

**Comment by ThomasWaldmann** [comment]
For the time when `?` is displayed, it is unclear whether it can actually make that connection.
It is enabled, but we did not try yet. So `?` is pretty right for that, IMHO.

And yes, I would also see `!` as a warning or error rather.

**Pull request merged**
